-- `audit_logs` already exists (created in 20260427000001_audit_logs.sql,
-- which also adds the append-only immutability trigger and matching
-- indexes). This migration duplicated that table verbatim under a
-- different migration id; left as a no-op to avoid dropping/recreating a
-- table other migrations already reference.
