/**
 * The registry API surface.
 *
 * Every call lives in a per-domain module under `lib/api/`, each one built on
 * the single `apiFetch` wrapper in `lib/api/client.ts`. This file is the barrel
 * that keeps `from "@/lib/api"` imports resolving, and it re-exports exactly
 * what it exported before the split — nothing more.
 */

import {
  fetchContracts,
  fetchAllContracts,
  advancedSearchContracts,
  fetchContract,
  fetchContractHealth,
  fetchContractAnalytics,
  fetchContractVersions,
  fetchContractAbi,
  fetchContractChangelog,
  fetchContractRecommendations,
  fetchContractInteractions,
  publishContract,
} from "./api/contracts";
import {
  fetchPublisher,
  fetchPublishers,
  fetchPublisherContracts,
} from "./api/publishers";
import { fetchNetworks } from "./api/networks";
import {
  fetchSearchSuggestions,
  semanticSearch,
  fetchContractSearchSuggestions,
  listFavoriteSearches,
  deleteFavoriteSearch,
} from "./api/search";
import { fetchActivityFeed } from "./api/activity";
import {
  fetchDependencyTree,
  fetchDependencyScanReport,
  triggerDependencyScan,
  fetchPackageDependencies,
  declarePackageDependencies,
} from "./api/dependencies";
import {
  fetchMetricCatalog,
  fetchMetricSeries,
  fetchCustomMetricCatalog,
  fetchCustomMetricSeries,
} from "./api/metrics";
import {
  generateReleaseNotes,
  listReleaseNotes,
  fetchReleaseNotes,
  updateReleaseNotes,
  publishReleaseNotes,
} from "./api/releaseNotes";
import { fetchDeprecationInfo, setDeprecation } from "./api/deprecation";
import { fetchTemplates } from "./api/templates";
import { fetchContractGraph, fetchContractLocalGraph } from "./api/graph";
import { fetchFormalVerificationResults } from "./api/verification";
import {
  fetchCompatibilityMatrix,
  runCompatibilityTest,
  fetchCompatibilityHistory,
  fetchCompatibilityNotifications,
  getCompatibilityExportUrl,
} from "./api/compatibility";
import {
  fetchComments,
  postComment,
  voteComment,
  flagComment,
} from "./api/comments";
import { fetchPreferences, updatePreferences } from "./api/preferences";
import {
  fetchCollaborativeReview,
  createCollaborativeReview,
  addReviewComment,
  updateReviewerStatus,
} from "./api/reviews";
import { fetchContractExamples, rateExample } from "./api/examples";
import { fetchMaintenanceWindow } from "./api/maintenance";
import { getStats } from "./api/stats";
import { fetchStats } from "./api/stats";
import { fetchAnalytics } from "./api/analytics";
import { trackEvent } from "./analytics";

// Every domain type lives in `types/`. They are re-exported here so that
// existing `from "@/lib/api"` imports keep resolving.
export type {
  ActivityFeedParams,
  ActivityFeedResponse,
  AnalyticsEvent,
  AnalyticsEventType,
  CollaborativeReview,
  Comment,
  CommentListResponse,
  CompatibilityEntry,
  CompatibilityHistoryEntry,
  CompatibilityHistoryResponse,
  CompatibilityMatrix,
  CompatibilityMatrixRow,
  CompatibilityNotification,
  CompatibilityTestEntry,
  CompatibilityTestMatrixResponse,
  CompatibilityTestStatus,
  CompatibilityTestSummary,
  Contract,
  ContractAbiResponse,
  ContractAnalyticsResponse,
  ContractChangelogEntry,
  ContractChangelogResponse,
  ContractExample,
  ContractGetResponse,
  ContractHealth,
  ContractInteractionResponse,
  ContractInteroperabilityResponse,
  ContractRecommendationsResponse,
  ContractSearchParams,
  ContractVersion,
  CreateCollaborativeReviewRequest,
  CustomMetricType,
  DependencyScanReport,
  DependencyScanStatus,
  DependencyTreeNode,
  DependencyVulnerabilityFinding,
  DeploymentStats,
  DeprecationInfo,
  DeprecationStatus,
  DiffSummary,
  FavoriteSearch,
  FormalVerificationFinding,
  FormalVerificationProperty,
  FormalVerificationPropertyDefinition,
  FormalVerificationPropertyResult,
  FormalVerificationReport,
  FormalVerificationSession,
  FunctionChange,
  GenerateReleaseNotesRequest,
  GraphEdge,
  GraphNode,
  GraphResponse,
  InteractionsListResponse,
  InteractionsQueryParams,
  InteractorStats,
  InteroperabilityCapability,
  InteroperabilityCapabilityKind,
  InteroperabilityProtocolMatch,
  InteroperabilitySuggestion,
  InteroperabilitySummary,
  LegacyStatsResponse,
  MaintenanceWindow,
  MaturityLevel,
  MetricCatalogEntry,
  MetricSample,
  MetricSeriesPoint,
  MetricSeriesResponse,
  Network,
  NetworkConfig,
  NetworkEndpoints,
  NetworkInfo,
  NetworkListResponse,
  NetworkStatus,
  PackageDependency,
  PackageDependencyInput,
  PaginatedResponse,
  ProofCertificate,
  PublishReleaseNotesRequest,
  PublishRequest,
  Publisher,
  QueryNode,
  RecommendationReason,
  RecommendedContract,
  ReleaseNotesResponse,
  ReleaseNotesStatus,
  RunCompatibilityTestRequest,
  SearchIntent,
  SearchIntentType,
  SearchSuggestion,
  SearchSuggestionsResponse,
  SemanticContractSearchResponse,
  SemanticSearchMetadata,
  Template,
  TemplateParameter,
  TimelineEntry,
  TopUser,
  UpdateReleaseNotesRequest,
  UserPreferences,
} from "@/types";

export { ApiError, NetworkError } from "./errors";

export {
  fetchContracts,
  fetchAllContracts,
  advancedSearchContracts,
  fetchContract,
  fetchContractHealth,
  fetchContractAnalytics,
  fetchContractVersions,
  fetchContractAbi,
  fetchContractChangelog,
  fetchContractRecommendations,
  fetchContractInteractions,
  publishContract,
  fetchPublisher,
  fetchPublishers,
  fetchPublisherContracts,
  fetchNetworks,
  fetchSearchSuggestions,
  semanticSearch,
  fetchContractSearchSuggestions,
  listFavoriteSearches,
  deleteFavoriteSearch,
  fetchActivityFeed,
  fetchDependencyTree,
  fetchDependencyScanReport,
  triggerDependencyScan,
  fetchPackageDependencies,
  declarePackageDependencies,
  fetchMetricCatalog,
  fetchMetricSeries,
  fetchCustomMetricCatalog,
  fetchCustomMetricSeries,
  generateReleaseNotes,
  listReleaseNotes,
  fetchReleaseNotes,
  updateReleaseNotes,
  publishReleaseNotes,
  fetchDeprecationInfo,
  setDeprecation,
  fetchTemplates,
  fetchContractGraph,
  fetchContractLocalGraph,
  fetchFormalVerificationResults,
  fetchCompatibilityMatrix,
  runCompatibilityTest,
  fetchCompatibilityHistory,
  fetchCompatibilityNotifications,
  getCompatibilityExportUrl,
  fetchComments,
  postComment,
  voteComment,
  flagComment,
  fetchPreferences,
  updatePreferences,
  fetchCollaborativeReview,
  createCollaborativeReview,
  addReviewComment,
  updateReviewerStatus,
  fetchContractExamples,
  rateExample,
  fetchMaintenanceWindow,
  getStats,
  trackEvent,
};

// ─── api namespace object ─────────────────────────────────────────────────────
// Provides `import { api } from "@/lib/api"` compatibility used across components.

export const api = {
  fetchContracts,
  fetchAllContracts,
  getContracts: fetchContracts,
  advancedSearchContracts,
  fetchContract,
  getContract: fetchContract,
  fetchContractHealth,
  getContractHealth: fetchContractHealth,
  fetchContractAnalytics,
  getContractAnalytics: fetchContractAnalytics,
  fetchContractVersions,
  getContractVersions: fetchContractVersions,
  fetchContractAbi,
  fetchAnalytics,
  getStats,
  fetchStats,
  getContractAbi: fetchContractAbi,
  fetchContractChangelog,
  getContractChangelog: fetchContractChangelog,
  fetchContractRecommendations,
  getContractRecommendations: fetchContractRecommendations,
  fetchContractInteractions,
  getContractInteractions: fetchContractInteractions,
  publishContract,
  fetchPublisher,
  getPublisher: fetchPublisher,
  fetchPublishers,
  getPublishers: fetchPublishers,
  fetchPublisherContracts,
  getPublisherContracts: fetchPublisherContracts,
  fetchNetworks,
  getNetworks: fetchNetworks,
  fetchSearchSuggestions,
  getSearchSuggestions: fetchSearchSuggestions,
  semanticSearch,
  fetchActivityFeed,
  getActivityFeed: fetchActivityFeed,
  fetchDependencyTree,
  getContractDependencies: fetchDependencyTree,
  fetchMetricCatalog,
  getMetricCatalog: fetchMetricCatalog,
  fetchMetricSeries,
  getMetricSeries: fetchMetricSeries,
  generateReleaseNotes,
  listReleaseNotes,
  fetchReleaseNotes,
  getReleaseNotes: fetchReleaseNotes,
  updateReleaseNotes,
  publishReleaseNotes,
  fetchDeprecationInfo,
  getDeprecationInfo: fetchDeprecationInfo,
  setDeprecation,
  fetchCollaborativeReview,
  getCollaborativeReview: fetchCollaborativeReview,
  createCollaborativeReview,
  addReviewComment,
  addCollaborativeComment: addReviewComment,
  updateReviewerStatus,
  fetchContractExamples,
  getContractExamples: fetchContractExamples,
  rateExample,
  fetchMaintenanceWindow,
  getMaintenanceWindow: fetchMaintenanceWindow,
  // Backward-compatible aliases for stats and templates
  fetchTemplates,
  getTemplates: fetchTemplates,
  // Backward-compatible aliases for graph methods
  fetchContractGraph,
  getContractGraph: fetchContractGraph,
  fetchContractLocalGraph,
  getContractLocalGraph: fetchContractLocalGraph,
  // Backward-compatible aliases for formal verification
  fetchFormalVerificationResults,
  getFormalVerificationResults: fetchFormalVerificationResults,
  // Dependency vulnerability scanning
  fetchDependencyScanReport,
  getDependencyScanReport: fetchDependencyScanReport,
  triggerDependencyScan,
  fetchPackageDependencies,
  declarePackageDependencies,
  // Backward-compatible aliases for compatibility testing
  fetchCompatibilityMatrix,
  getCompatibilityMatrix: fetchCompatibilityMatrix,
  runCompatibilityTest,
  fetchCompatibilityHistory,
  getCompatibilityHistory: fetchCompatibilityHistory,
  fetchCompatibilityNotifications,
  getCompatibilityNotifications: fetchCompatibilityNotifications,
  getCompatibilityExportUrl,
  // Backward-compatible aliases for comments
  fetchComments,
  getComments: fetchComments,
  postComment,
  voteComment,
  flagComment,
  listFavoriteSearches,
  deleteFavoriteSearch,
  // Backward-compatible aliases for preferences
  fetchPreferences,
  getPreferences: fetchPreferences,
  updatePreferences,
  // Backward-compatible aliases for search suggestions
  fetchContractSearchSuggestions,
  getContractSearchSuggestions: fetchContractSearchSuggestions,
  // Backward-compatible aliases for custom metrics
  fetchCustomMetricCatalog,
  getCustomMetricCatalog: fetchCustomMetricCatalog,
  fetchCustomMetricSeries,
  getCustomMetricSeries: fetchCustomMetricSeries,
};
